dns_provider:
  cloudflare:
    api_token: "your-api-token"
    zone_id: "your-zone-id"
    records:
      - name: "domain.xyz"
        id: a123
        type: a
      - name: "*.domain.xyz"
        id: b123
        type: a
